{"uuid": "0025d257-e0a5-4727-a09c-9386d73b7a36", "children": ["b61df399-d93b-416e-b3ff-d25769f8a2d9"], "befores": [{"name": "setup_alerts_page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=140.0.7339.208)\nStacktrace:\n0   chromedriver                        0x000000010ebccf08 chromedriver + 5934856\n1   chromedriver                        0x000000010ebc4c9a chromedriver + 5901466\n2   chromedriver                        0x000000010e690ade chromedriver + 445150\n3   chromedriver                        0x000000010e663ca0 chromedriver + 261280\n4   chromedriver                        0x000000010e716c65 chromedriver + 994405\n5   chromedriver                        0x000000010e733a9b chromedriver + 1112731\n6   chromedriver                        0x000000010e70e503 chromedriver + 959747\n7   chromedriver                        0x000000010e6d7731 chromedriver + 735025\n8   chromedriver                        0x000000010e6d8ee1 chromedriver + 741089\n9   chromedriver                        0x000000010eb96360 chromedriver + 5710688\n10  chromedriver                        0x000000010eb98c00 chromedriver + 5721088\n11  chromedriver                        0x000000010eb9877b chromedriver + 5719931\n12  chromedriver                        0x000000010eb990a5 chromedriver + 5722277\n13  chromedriver                        0x000000010eb7be97 chromedriver + 5602967\n14  chromedriver                        0x000000010eb99372 chromedriver + 5722994\n15  chromedriver                        0x000000010eb6f584 chromedriver + 5551492\n16  chromedriver                        0x000000010ebb4d28 chromedriver + 5836072\n17  chromedriver                        0x000000010ebb4e85 chromedriver + 5836421\n18  chromedriver                        0x000000010ebc4823 chromedriver + 5900323\n19  libsystem_pthread.dylib             0x00007ff81aad4e59 _pthread_start + 115\n20  libsystem_pthread.dylib             0x00007ff81aad0857 thread_start + 15\n\n", "trace": "  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/_pytest/fixtures.py\", line 930, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/pvon/Documents/estagio-automation/tests/test_alert.py\", line 9, in setup_alerts_page\n    home_page.click_alert_frame_windows_card()\n  File \"/Users/pvon/Documents/estagio-automation/pages/alert_pages.py\", line 18, in click_alert_frame_windows_card\n    element = self.driver.find_element(*self.alerts_frames_windows_card)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 926, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 458, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1759156490905, "stop": 1759156491041}], "start": 1759156490905, "stop": 1759156491083}