{"uuid": "c05913fb-9888-4118-afd9-0f04e861cac9", "children": ["ce586ef7-ba1c-414f-9d59-f143604f5c08"], "befores": [{"name": "setup_alerts_page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=140.0.7339.208)\nStacktrace:\n0   chromedriver                        0x000000010e9eaf08 chromedriver + 5934856\n1   chromedriver                        0x000000010e9e2c9a chromedriver + 5901466\n2   chromedriver                        0x000000010e4aeade chromedriver + 445150\n3   chromedriver                        0x000000010e481ca0 chromedriver + 261280\n4   chromedriver                        0x000000010e534c65 chromedriver + 994405\n5   chromedriver                        0x000000010e551a9b chromedriver + 1112731\n6   chromedriver                        0x000000010e52c503 chromedriver + 959747\n7   chromedriver                        0x000000010e4f5731 chromedriver + 735025\n8   chromedriver                        0x000000010e4f6ee1 chromedriver + 741089\n9   chromedriver                        0x000000010e9b4360 chromedriver + 5710688\n10  chromedriver                        0x000000010e9b6c00 chromedriver + 5721088\n11  chromedriver                        0x000000010e9b677b chromedriver + 5719931\n12  chromedriver                        0x000000010e9b70a5 chromedriver + 5722277\n13  chromedriver                        0x000000010e999e97 chromedriver + 5602967\n14  chromedriver                        0x000000010e9b7372 chromedriver + 5722994\n15  chromedriver                        0x000000010e98d584 chromedriver + 5551492\n16  chromedriver                        0x000000010e9d2d28 chromedriver + 5836072\n17  chromedriver                        0x000000010e9d2e85 chromedriver + 5836421\n18  chromedriver                        0x000000010e9e2823 chromedriver + 5900323\n19  libsystem_pthread.dylib             0x00007ff81aad4e59 _pthread_start + 115\n20  libsystem_pthread.dylib             0x00007ff81aad0857 thread_start + 15\n\n", "trace": "  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/_pytest/fixtures.py\", line 930, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/pvon/Documents/estagio-automation/tests/test_alert.py\", line 9, in setup_alerts_page\n    home_page.click_alert_frame_windows_card()\n  File \"/Users/pvon/Documents/estagio-automation/pages/alert_pages.py\", line 18, in click_alert_frame_windows_card\n    element = self.driver.find_element(*self.alerts_frames_windows_card)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 926, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 458, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1759156488906, "stop": 1759156489157}], "start": 1759156488906, "stop": 1759156489198}